add positional parameter scripts

diff --git a/sys_info_page b/sys_info_page
--- a/sys_info_page
+++ b/sys_info_page
@@ -2,6 +2,7 @@
 
 # Program to output a system information page
 
+PROGNAME=$(basename $0)
 TITLE="System Information Report for $HOSTNAME"
 CURRENT_TIME=$(date +"%x %r %Z")
 TIME_STAMP="Generated $CURRENT_TIME, by $USER"
@@ -30,18 +31,84 @@ report_home_space(){
 	return
 }
 
-cat << _EOF_
-<html>
-	<head>
-		<title>$TITLE</title>
-	</head>
-	<body>
-		<h1>$TITLE</h1>
-		<p>$TIME_STAMP</p>
-		$(report_uptime)
-		$(report_disk_space)
-		$(report_home_space)
-	</body>
-</html>
-_EOF_
+usage () {
+	echo "$PROGNAME: usage: $PROGNAME [-f file | -i}"
+	return
+}
 
+write_html_page () {
+	cat <<- _EOF_
+	<html>
+		<head>
+			<title>$TITLE</title>
+		</head>
+		<body>
+			<h1>$TITLE</h1>
+			<p>$TIME_STAMP</p>
+			$(report_uptime)
+			$(report_disk_space)
+			$(report_home_space)
+		</body>
+	</html>
+	_EOF_
+	return
+}
+
+# process command line options
+
+interactive=
+filename=
+
+while [[ -n $1 ]]; do
+	case $1 in
+		-f | --file)		shift
+					filename=$1
+					;;
+		-i | --interactive)	interactive=1
+					;;
+		-h | --help)		usage
+					exit
+					;;
+		*)			usage >&2
+					exit 1
+					;;
+	esac
+	shift
+done
+
+# interactive mode
+
+if [[ -n $interactive ]]; then
+	while true; do
+		read -p "Enter name of output file: " filename
+		if [[ -e $filename ]]; then
+			read -p "'$filename' exists. Overwrite? [y/n/q] > "
+			case $REPLY in
+				Y|y)	break
+					;;
+				Q|q) 	echo "Program terminated."
+					exit
+					;;
+				*)	continue
+					;;
+			esac
+		elif [[ -z $filename ]]; then
+			continue
+		else
+			break
+		fi
+	done
+fi
+
+# output file page
+
+if [[ -n $filename ]]; then
+	if touch $filename && [[ -f $filename ]]; then
+		write_html_page > $filename
+	else
+		echo "$PROGNAME: Cannot write file '$filename'" >&2
+		exit 1
+	fi
+else
+	write_html_page
+fi
